/**
 * ASIP SEO Agent — OpenClaw Skill
 * ================================
 * This skill polls ASIP for newly completed SEO campaigns and
 * sends you a WhatsApp/Telegram notification via OpenClaw with
 * a direct link to review and approve the posts.
 *
 * HOW TO USE IN OPENCLAW:
 * 1. Install OpenClaw: curl -fsSL https://openclaw.ai/install.sh | bash
 * 2. Copy this file to your OpenClaw skills directory
 * 3. Set the config variables below (or use environment variables)
 * 4. Tell OpenClaw: "Run the ASIP SEO agent every 5 minutes"
 *
 * WHAT IT DOES:
 * - Every 5 minutes, checks ASIP for campaigns in 'awaiting_approval' status
 * - For each new campaign, sends you a message with:
 *     "🎯 SEO posts ready for [Product Name]! 4 platform posts (Instagram, Facebook,
 *      LinkedIn, Google) generated by NVIDIA. Review here: http://localhost:7801/seo/campaigns/5"
 * - You click the link → approve in browser → done
 */

import fetch from 'node-fetch';

// ─── Configuration ─────────────────────────────────────────────────────────
const CONFIG = {
    // ASIP instance URL (change if not running locally)
    asipUrl: process.env.ASIP_URL || 'http://localhost:7801',

    // Webhook token from ASIP .env (SEO_WEBHOOK_TOKEN)
    webhookToken: process.env.SEO_WEBHOOK_TOKEN || 'PASTE_YOUR_TOKEN_HERE',

    // Poll interval in milliseconds (5 minutes)
    pollInterval: 5 * 60 * 1000,

    // Workspace ID to monitor (check ASIP URL — it's in /workspaces/{id}/)
    workspaceId: process.env.ASIP_WORKSPACE_ID || '1',
};

// ─── State ──────────────────────────────────────────────────────────────────
const notifiedCampaigns = new Set();

// ─── Main ────────────────────────────────────────────────────────────────────
async function checkForNewCampaigns() {
    try {
        const url = `${CONFIG.asipUrl}/api/v1/workspaces/${CONFIG.workspaceId}/seo/campaigns?status=awaiting_approval`;

        const response = await fetch(url, {
            headers: {
                'Accept': 'application/json',
                'X-Webhook-Token': CONFIG.webhookToken,
            },
        });

        if (!response.ok) {
            console.error(`ASIP API error: ${response.status}`);
            return;
        }

        const json = await response.json();
        const campaigns = json.data || [];

        for (const campaign of campaigns) {
            if (notifiedCampaigns.has(campaign.id)) {
                continue; // Already notified about this one
            }

            notifiedCampaigns.add(campaign.id);

            await sendNotification(campaign);
        }

    } catch (err) {
        console.error('SEO agent check failed:', err.message);
    }
}

async function sendNotification(campaign) {
    const productName = campaign.product?.title
        ? campaign.product.title.substring(0, 50) + (campaign.product.title.length > 50 ? '…' : '')
        : `Product #${campaign.product?.id}`;

    const reviewUrl = `${CONFIG.asipUrl}/seo/campaigns/${campaign.id}`;
    const postsCount = campaign.posts_count || 4;

    // ── Message sent via OpenClaw to your WhatsApp/Telegram ──
    const message = [
        '🎯 *SEO Posts Ready for Review!*',
        '',
        `📦 *Product:* ${productName}`,
        `✨ *${postsCount} posts generated* by NVIDIA Nemotron`,
        '   • 📸 Instagram caption + hashtags',
        '   • 📘 Facebook story post',
        '   • 💼 LinkedIn professional post',
        '   • 🔍 Google Business post',
        '',
        '👆 *Tap to Review & Approve:*',
        reviewUrl,
        '',
        '_Approve individually or tap "Approve All" for quick action._',
    ].join('\n');

    // ── OpenClaw messaging API ──────────────────────────────────────────────
    // OpenClaw exposes a local API for sending messages via your connected
    // messaging apps (WhatsApp, Telegram, Discord, etc.)
    // The exact endpoint depends on your OpenClaw version.
    //
    // Option A: Via OpenClaw's local API (recommended)
    try {
        const openclaw = await fetch('http://localhost:3000/api/message/send', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                channel: 'whatsapp',   // or 'telegram', 'discord', 'slack'
                message: message,
            }),
        });

        if (openclaw.ok) {
            console.log(`✅ Notified: Campaign #${campaign.id} — ${productName}`);
            return;
        }
    } catch {
        // OpenClaw API not available — fall through to console output
    }

    // Option B: Console fallback (when running standalone without OpenClaw)
    console.log('\n' + '═'.repeat(60));
    console.log(message);
    console.log('═'.repeat(60) + '\n');
}

// ─── Notify ASIP that we've sent the notification ────────────────────────────
async function markNotified(campaignId) {
    try {
        await fetch(`${CONFIG.asipUrl}/api/seo/webhook/notify`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Webhook-Token': CONFIG.webhookToken,
            },
            body: JSON.stringify({
                campaign_id: campaignId,
                event: 'notified',
            }),
        });
    } catch {
        // Non-critical
    }
}

// ─── Start ───────────────────────────────────────────────────────────────────
console.log('🤖 ASIP SEO Agent started');
console.log(`   Monitoring: ${CONFIG.asipUrl}`);
console.log(`   Workspace:  #${CONFIG.workspaceId}`);
console.log(`   Poll every: ${CONFIG.pollInterval / 1000}s\n`);

// Run immediately, then on interval
checkForNewCampaigns();
setInterval(checkForNewCampaigns, CONFIG.pollInterval);
