<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useWorkspaceStore } from '@/stores/workspace'
import { useSeoStore } from '@/stores/seo'
import { useToastStore } from '@/stores/toast'
import type { SeoPost } from '@/stores/seo'

const route          = useRoute()
const router         = useRouter()
const workspaceStore = useWorkspaceStore()
const seoStore       = useSeoStore()
const toast          = useToastStore()

const activePost    = ref<SeoPost | null>(null)
const editingPost   = ref<SeoPost | null>(null)
const editedCaption = ref('')
const copying       = ref<number | null>(null)

const STATUS_COLORS: Record<string, string> = {
    draft:    'bg-gray-100 text-gray-600',
    approved: 'bg-green-100 text-green-700',
    rejected: 'bg-red-100 text-red-600',
}

onMounted(async () => {
    const wsId = workspaceStore.current?.id
    const id   = Number(route.params.id)
    if (!wsId || !id) return
    await seoStore.fetchCampaign(wsId, id)
    // Auto-select first post
    if (seoStore.current?.posts?.length) {
        activePost.value = seoStore.current.posts[0]
    }
})

const campaign = computed(() => seoStore.current)
const allApproved = computed(() =>
    campaign.value?.posts?.every(p => p.status === 'approved' || p.status === 'rejected') ?? false
)

function selectPost(post: SeoPost) {
    activePost.value = post
    editingPost.value = null
}

function startEdit(post: SeoPost) {
    editingPost.value = post
    editedCaption.value = post.edited_caption ?? post.caption ?? ''
}

async function saveApprove() {
    if (!editingPost.value) return
    try {
        await seoStore.approvePost(editingPost.value.id, editedCaption.value || undefined)
        toast.success('Post approved!')
        editingPost.value = null
    } catch {
        toast.error('Failed to approve post')
    }
}

async function quickApprove(post: SeoPost) {
    try {
        await seoStore.approvePost(post.id)
        toast.success(`${seoStore.PLATFORM_LABELS[post.platform]} post approved!`)
    } catch {
        toast.error('Failed to approve')
    }
}

async function rejectPost(post: SeoPost) {
    try {
        await seoStore.rejectPost(post.id)
        toast.info('Post rejected')
    } catch {
        toast.error('Failed to reject')
    }
}

async function copyToClipboard(post: SeoPost) {
    const text = [
        post.edited_caption ?? post.caption,
        post.hashtags,
    ].filter(Boolean).join('\n\n')

    await navigator.clipboard.writeText(text)
    copying.value = post.id
    toast.success('Copied to clipboard!')
    setTimeout(() => { copying.value = null }, 2000)
}

const PLATFORM_ICONS: Record<string, string> = {
    instagram: '📸', facebook: '📘', linkedin: '💼', google_business: '🔍',
}
const PLATFORM_GUIDE: Record<string, string> = {
    instagram:       'Copy caption + hashtags → paste in Instagram app',
    facebook:        'Copy post text → paste in Facebook Create Post',
    linkedin:        'Copy post → paste in LinkedIn Share box',
    google_business: 'Copy post → Add Update in Google Business Profile',
}
</script>

<template>
    <div class="p-6">
        <!-- Header -->
        <div class="flex items-center gap-3 mb-6">
            <RouterLink to="/seo" class="text-sm text-indigo-600 hover:underline">← SEO Campaigns</RouterLink>
            <span class="text-gray-300">|</span>
            <div v-if="campaign">
                <h1 class="text-xl font-bold text-gray-900 truncate">{{ campaign.product?.title }}</h1>
                <p class="text-xs text-gray-500 mt-0.5">
                    {{ campaign.product?.asin }} · Generated by {{ campaign.ai_provider ?? 'NVIDIA' }}
                </p>
            </div>
        </div>

        <div v-if="!campaign" class="text-gray-400 text-sm text-center py-10">Loading…</div>

        <!-- Generating state -->
        <div v-else-if="campaign.status === 'generating'"
            class="bg-white rounded-xl border border-gray-200 p-10 text-center">
            <div class="text-5xl mb-4">⚡</div>
            <h2 class="text-lg font-semibold text-gray-900 mb-2">NVIDIA is generating your content</h2>
            <p class="text-sm text-gray-500 mb-2">Researching trends → Writing 4 platform posts → Creating image prompts</p>
            <p class="text-xs text-gray-400">Usually takes 30–60 seconds. Page will update automatically.</p>
            <div class="mt-4 flex justify-center gap-2">
                <div class="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style="animation-delay:0ms" />
                <div class="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style="animation-delay:150ms" />
                <div class="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style="animation-delay:300ms" />
            </div>
        </div>

        <!-- Failed state -->
        <div v-else-if="campaign.status === 'failed'"
            class="bg-red-50 rounded-xl border border-red-200 p-6 text-center">
            <p class="text-red-700 font-medium mb-2">Content generation failed</p>
            <p class="text-sm text-red-600 mb-4">Check that NVIDIA_API_KEY is configured in .env</p>
        </div>

        <!-- Posts review UI -->
        <template v-else-if="campaign.posts?.length">

            <!-- Trend insight bar -->
            <div v-if="campaign.trend_data"
                class="bg-gradient-to-r from-purple-50 to-indigo-50 border border-purple-200 rounded-xl p-4 mb-6">
                <p class="text-xs font-semibold text-purple-700 mb-1">🔥 Trend Research by NVIDIA</p>
                <p class="text-sm text-purple-800">
                    <strong>Angle:</strong> {{ campaign.trend_data.content_angle }}
                    · <strong>Context:</strong> {{ campaign.trend_data.seasonal_context }}
                </p>
                <div v-if="campaign.trend_data.trending_topics?.length" class="flex flex-wrap gap-1 mt-2">
                    <span v-for="t in (campaign.trend_data.trending_topics as string[])" :key="t"
                        class="px-2 py-0.5 bg-purple-100 text-purple-700 rounded-full text-xs">
                        {{ t }}
                    </span>
                </div>
            </div>

            <!-- Bulk approve all -->
            <div v-if="!allApproved" class="flex justify-end gap-2 mb-4">
                <button
                    @click="campaign.posts?.filter(p => p.status === 'draft').forEach(p => quickApprove(p))"
                    class="px-4 py-1.5 text-sm bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors">
                    ✓ Approve All
                </button>
            </div>

            <!-- All approved callout -->
            <div v-if="allApproved"
                class="bg-green-50 border border-green-200 rounded-xl p-4 mb-6 flex items-center gap-3">
                <span class="text-2xl">🎉</span>
                <div>
                    <p class="text-sm font-semibold text-green-800">All posts approved!</p>
                    <p class="text-xs text-green-700">Copy each post and share on your social media accounts.</p>
                </div>
            </div>

            <div class="flex gap-6">
                <!-- Platform sidebar -->
                <div class="w-48 flex-shrink-0 space-y-2">
                    <button v-for="post in campaign.posts" :key="post.id"
                        @click="selectPost(post)"
                        :class="['w-full text-left px-3 py-3 rounded-xl border-2 transition-colors',
                            activePost?.id === post.id
                                ? 'border-indigo-500 bg-indigo-50'
                                : 'border-gray-200 bg-white hover:border-gray-300']">
                        <div class="flex items-center justify-between">
                            <div class="flex items-center gap-2">
                                <span class="text-lg">{{ PLATFORM_ICONS[post.platform] }}</span>
                                <span class="text-xs font-medium text-gray-700">
                                    {{ seoStore.PLATFORM_LABELS[post.platform] }}
                                </span>
                            </div>
                            <span :class="['w-2 h-2 rounded-full', {
                                'bg-green-500': post.status === 'approved',
                                'bg-red-400':   post.status === 'rejected',
                                'bg-gray-300':  post.status === 'draft',
                            }]" />
                        </div>
                        <span :class="['text-xs mt-1 block', STATUS_COLORS[post.status]]">
                            {{ post.status === 'draft' ? 'Needs review' : post.status }}
                        </span>
                    </button>
                </div>

                <!-- Post content panel -->
                <div class="flex-1 bg-white rounded-xl border border-gray-200 p-5" v-if="activePost">
                    <div class="flex items-center justify-between mb-4">
                        <div class="flex items-center gap-2">
                            <span class="text-xl">{{ PLATFORM_ICONS[activePost.platform] }}</span>
                            <h3 class="font-semibold text-gray-900">
                                {{ seoStore.PLATFORM_LABELS[activePost.platform] }}
                            </h3>
                            <span :class="['px-2 py-0.5 rounded-full text-xs font-medium', STATUS_COLORS[activePost.status]]">
                                {{ activePost.status }}
                            </span>
                        </div>
                        <div class="flex gap-2">
                            <!-- Copy -->
                            <button @click="copyToClipboard(activePost)"
                                class="px-3 py-1.5 text-xs border border-gray-300 rounded-lg hover:bg-gray-50 flex items-center gap-1 transition-colors">
                                {{ copying === activePost.id ? '✓ Copied!' : '📋 Copy' }}
                            </button>
                            <!-- Edit & Approve -->
                            <button v-if="activePost.status === 'draft'"
                                @click="startEdit(activePost)"
                                class="px-3 py-1.5 text-xs border border-indigo-300 text-indigo-700 rounded-lg hover:bg-indigo-50 transition-colors">
                                ✏️ Edit & Approve
                            </button>
                            <!-- Quick Approve -->
                            <button v-if="activePost.status === 'draft'"
                                @click="quickApprove(activePost)"
                                class="px-3 py-1.5 text-xs bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors">
                                ✓ Approve
                            </button>
                            <!-- Reject -->
                            <button v-if="activePost.status === 'draft'"
                                @click="rejectPost(activePost)"
                                class="px-3 py-1.5 text-xs text-red-600 border border-red-200 rounded-lg hover:bg-red-50 transition-colors">
                                ✗ Reject
                            </button>
                        </div>
                    </div>

                    <!-- How to post guide -->
                    <div class="text-xs text-gray-400 bg-gray-50 rounded-lg px-3 py-2 mb-4">
                        📱 {{ PLATFORM_GUIDE[activePost.platform] }}
                    </div>

                    <!-- Edit mode -->
                    <div v-if="editingPost?.id === activePost.id" class="mb-4">
                        <label class="block text-xs font-medium text-gray-600 mb-1">Edit caption</label>
                        <textarea v-model="editedCaption" rows="6"
                            class="w-full border border-indigo-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-y" />
                        <div class="flex gap-2 mt-2">
                            <button @click="editingPost = null" class="px-3 py-1.5 text-xs text-gray-600 border border-gray-300 rounded-lg">Cancel</button>
                            <button @click="saveApprove" class="px-4 py-1.5 text-xs bg-green-600 text-white rounded-lg hover:bg-green-700">Save & Approve</button>
                        </div>
                    </div>

                    <!-- View mode -->
                    <template v-else>
                        <!-- Caption -->
                        <div class="mb-4">
                            <p class="text-xs font-medium text-gray-500 mb-1">Caption</p>
                            <div class="bg-gray-50 rounded-lg px-4 py-3 text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">
                                {{ activePost.edited_caption ?? activePost.caption }}
                            </div>
                        </div>

                        <!-- Hashtags -->
                        <div v-if="activePost.hashtags" class="mb-4">
                            <p class="text-xs font-medium text-gray-500 mb-1">Hashtags</p>
                            <div class="flex flex-wrap gap-1">
                                <span v-for="tag in activePost.hashtags.split(' ').filter(Boolean)" :key="tag"
                                    class="px-2 py-0.5 bg-indigo-100 text-indigo-700 rounded-full text-xs font-mono">
                                    {{ tag }}
                                </span>
                            </div>
                        </div>

                        <!-- Image prompt -->
                        <div v-if="activePost.image_prompt" class="mb-4">
                            <p class="text-xs font-medium text-gray-500 mb-1">Image Prompt (use with DALL-E / Midjourney)</p>
                            <div class="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 text-xs text-amber-800 italic">
                                {{ activePost.image_prompt }}
                            </div>
                        </div>
                    </template>
                </div>
            </div>
        </template>
    </div>
</template>
