<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11px; color: #111; margin: 0; padding: 20px; }
    h1 { font-size: 18px; color: #1e40af; margin-bottom: 4px; }
    h2 { font-size: 13px; color: #374151; margin-top: 20px; margin-bottom: 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    .meta { font-size: 10px; color: #6b7280; margin-bottom: 16px; }
    .product-info { background: #f3f4f6; padding: 12px; border-radius: 4px; margin-bottom: 16px; }
    .score-big { font-size: 48px; font-weight: bold; color: #1e40af; text-align: center; }
    .score-tier { text-align: center; font-size: 14px; color: #6b7280; margin-top: -8px; margin-bottom: 12px; }
    .dim-grid { display: table; width: 100%; }
    .dim-cell { display: table-cell; width: 20%; text-align: center; padding: 8px 4px; border: 1px solid #e5e7eb; }
    .dim-label { font-size: 9px; color: #6b7280; }
    .dim-score { font-size: 14px; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; margin-top: 8px; }
    th { background: #1e40af; color: white; padding: 6px 8px; text-align: left; }
    td { padding: 5px 8px; border-bottom: 1px solid #f3f4f6; }
    tr:nth-child(even) td { background: #f9fafb; }
    .issue { color: #dc2626; }
    .pass { color: #059669; }
    .kw-chip { display: inline-block; background: #ede9fe; color: #5b21b6; padding: 1px 6px; border-radius: 10px; font-size: 9px; margin: 1px; }
    .footer { margin-top: 24px; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 8px; }
</style>
</head>
<body>

<h1>ASIP — Listing Analysis Report</h1>
<div class="meta">
    Product: <strong>{{ $product->asin }}</strong> &nbsp;|&nbsp;
    {{ $product->title ? mb_substr($product->title, 0, 80).(mb_strlen($product->title) > 80 ? '…' : '') : 'No title' }}
    &nbsp;|&nbsp; Generated: {{ $generated }}
</div>

<div class="product-info">
    <strong>Brand:</strong> {{ $product->brand ?? '—' }} &nbsp;&nbsp;
    <strong>Category:</strong> {{ $product->category ?? '—' }} &nbsp;&nbsp;
    <strong>Price:</strong> ₹{{ number_format((float)$product->price, 2) }} &nbsp;&nbsp;
    <strong>Rating:</strong> {{ $product->rating ? $product->rating.'★ ('.$product->review_count.' reviews)' : 'No data' }}
</div>

@if (!empty($score))
<div class="score-big">{{ $score['total'] ?? 0 }}</div>
<div class="score-tier">out of 100</div>

<h2>Score Breakdown</h2>
<div class="dim-grid">
@foreach(['title' => 'Title (25)', 'bullets' => 'Bullets (25)', 'description' => 'Description (20)', 'reviews' => 'Reviews (15)', 'keywords' => 'Keywords (15)'] as $key => $label)
    @php $dim = $score['dimensions'][$key] ?? [] @endphp
    <div class="dim-cell">
        <div class="dim-label">{{ $label }}</div>
        <div class="dim-score" style="color: {{ ($dim['score'] ?? 0) / ($dim['max'] ?? 1) >= 0.8 ? '#059669' : (($dim['score'] ?? 0) / ($dim['max'] ?? 1) >= 0.5 ? '#d97706' : '#dc2626') }}">
            {{ $dim['score'] ?? 0 }}/{{ $dim['max'] ?? 0 }}
        </div>
    </div>
@endforeach
</div>

<h2>Issues & Recommendations</h2>
<table>
    <tr><th>Dimension</th><th>Finding</th><th>Type</th></tr>
    @foreach(['title' => 'Title', 'bullets' => 'Bullets', 'description' => 'Description', 'reviews' => 'Reviews', 'keywords' => 'Keywords'] as $key => $label)
        @php $dim = $score['dimensions'][$key] ?? [] @endphp
        @foreach($dim['passes'] ?? [] as $pass)
            <tr><td>{{ $label }}</td><td class="pass">✓ {{ $pass }}</td><td class="pass">Pass</td></tr>
        @endforeach
        @foreach($dim['issues'] ?? [] as $issue)
            <tr><td>{{ $label }}</td><td class="issue">✗ {{ $issue }}</td><td class="issue">Issue</td></tr>
        @endforeach
    @endforeach
</table>
@endif

@if (!empty($keywords) && count($keywords) > 0)
<h2>Top Keywords Extracted</h2>
<div style="margin-top: 8px;">
    @foreach($keywords->take(30) as $kw)
        <span class="kw-chip">{{ $kw->keyword }} ({{ $kw->frequency }})</span>
    @endforeach
</div>
@endif

@if (!empty($ai_hints['optimization_suggestions']))
<h2>AI Optimization Suggestions</h2>
<table>
    <tr><th>Field</th><th>Priority</th><th>Issue</th><th>Suggestion</th></tr>
    @foreach(array_slice($ai_hints['optimization_suggestions'], 0, 10) as $s)
    <tr>
        <td>{{ $s['field'] ?? '' }}</td>
        <td style="color: {{ ($s['priority'] ?? '') === 'high' ? '#dc2626' : '#d97706' }}">{{ strtoupper($s['priority'] ?? '') }}</td>
        <td>{{ $s['issue'] ?? '' }}</td>
        <td>{{ $s['suggestion'] ?? '' }}</td>
    </tr>
    @endforeach
</table>
@endif

<div class="footer">Generated by ASIP — Amazon Seller Intelligence Platform &nbsp;|&nbsp; {{ now()->toISOString() }}</div>
</body>
</html>
